#!/bin/bash

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

# Exit immediately if a command exits with a non-zero status
set -e

# Store a local variable of the scripts current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${DIR}/setup
${DIR}/bootstrap

echo "==> Running tests..."

npm run build
npm run test -- --watchAll=false --bail
npm run e2e

echo "==> Tests complete."
